development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: dummy_development

test:
  adapter: test

production:
  adapter: any_cable
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: larvata_cable_production
